### ISSUE TITLE
Problem with parametrisation of the report

### ISSUE THREAD

**Issue by DatViseR** [DatViseR/MitoCode_R_Workshops#1]
`reproducible_tab <- NHANES %>% filter(Education == "params$education") %>% 
                      group_by(params$group_var) %>% 
                      summarize(proportion = mean(
                               params$analysis_var == "Yes", na.rm = TRUE)
                                                              ) `

@vanilink I don't know why this table inside the workshop_3 markdown file is not rendered properly?

**Comment by DatViseR** [comment]
Thanks to @vanilink I have learned about "tidy evaluation" and "indirection issues" when using dplyr chain commands inside functions. Thanks for the changes!

**Comment by DatViseR** [comment]
Nevertheless, the proper table is still not produced. After introducing:

`reproducible_tab <- NHANES %>% filter(Education == "params$education") %>% 
                      group_by(.data[[params$group_var]]) %>% 
                      summarize(proportion = mean(
                               .data[[params$analysis_var]] == "Yes", na.rm = TRUE)
                                                              ) `

Now the following error appears: Factor `Gender` contains implicit NA, consider using `forcats::fct_explicit_na . This is strange as the same nonreproducible table code does not have a problem with it:

`smoking <- NHANES %>% filter(Education == "Some College") %>% 
                      group_by(Gender)%>% 
                      summarize(proportion = mean(
                               SmokeNow == "Yes", na.rm = TRUE)
                               ) 
smoking`

**Comment by DatViseR** [comment]
`anyNA(NHANES$Gender)
[1] FALSE`

**Comment by DatViseR** [comment]
I have updated dplyr library but still the table is not produced although there is no warning about NA

**Comment by vanilink** [comment]
Hi @DatViseR I believe the quotes around params$education were the problem. Once you put something in quotes it will be translated as a literal string (so instead of taking whatever is inside params$education, it will just write "params$education" as a string) - hope this helped!

**Comment by DatViseR** [comment]
Of course, that is so easy I do not know why I missed that I focused on the problems with parameters.....we may also use as. string() when needed but here it already is a string so no problem...
